strengthPlus:
  pluginName: '&e[&b&lStrengthPlus&e]'
  # 是否允许调试模式
  debug: true
  # 强化lore标题
  title: '&b[强化等级]:'
  # 强化lore分割线长度
  divider: '----------------'
  # 强化lore等级标识（单一等级标签）
  levelIcon: '✡'
  # 每几个等级标识一换行
  nextLineCount: 10
  # 通知
  notify:
    #成功时通知
    success: '强化成功'
    #失败时通知
    fail: '强化失败'
  broadcast:
    success: '&2恭喜%player%将他的装备强化到%level%级'
    safe: '&5很遗憾，%player%在将他的装备强化到%level%级的时候强化炉发生了爆炸，好在装备保护强化券保护了装备没有被摧毁！'
    fail: '&4很遗憾，%player%在将他的装备强化到%level%级的时候强化炉发生了爆炸，装备被摧毁了！'


